[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gineos_presale = "5fafMD9vnGUFY9oSwJaavHWWq5hovW1MNih1xTnvWGq8"
[programs.devnet]
gineos_presale = "5fafMD9vnGUFY9oSwJaavHWWq5hovW1MNih1xTnvWGq8"
[programs.testnet]
gineos_presale = "5fafMD9vnGUFY9oSwJaavHWWq5hovW1MNih1xTnvWGq8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = './wallet/devdxeX3u8KKXLbXbQmCJUBcih3mi9uwReetoy7pweA.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
